number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]№_`{|}~ €₽"
lang_char: 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюяАаӔӕ'
experiment_name: 'ru_filtered'
train_data: '/content/EasyOCR/trainer/all_data/imgs_train'
valid_data: '/content/EasyOCR/trainer/all_data/imgs_val'
manualSeed: 1111
workers: 6
num_class: 117
batch_size: 64 #32 
num_iter: 15000 
valInterval: 200
saved_model: 'best_accuracy_t.pth'
FT: True
optim: False
lr: 1
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 3
select_data: 'train'
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 68 
imgH: 100
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
data_filtering_off: False
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'Attn'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False 